name: Black Autoformatting

on:
    push:
    pull_request:

jobs:
    format:
        name: Black Autoformatting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Black Check
              run: black *.py && black cogs/*.py
